version: 2
updates:
  # Keep container base images updated
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/proxy"
    schedule:
      interval: "weekly"
